name: smart_uis
name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.0.0
  flutter_localizations: 
    sdk: flutter 
  sqflite: ^2.3.3 
  path_provider: ^2.1.3      

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/avatar.jpeg
    - assets/logo.jpeg
    - assets/hielo.jpeg
    - assets/fire.jpeg
    - assets/hielo.png


 


